void server (void);
void doserv (void);
void makehelp (void);
void makelist (short type, short sort);
void makestatus (struct link *blink);
void makelinks (char *areaname);
void changearea (struct uplname *areas);
short seekarea (char *echolist, char *area);
void chareacfg (struct uplname *areas, char *file);
void changelink (struct link *blink);
void chlinkcfg (struct link *blink, char *file);
void makemsg (short handle, char *what, char *templ);
short getweight (struct myaddr *address);
void swapaddr (struct myaddr *first, struct myaddr *second);
void areasort (short sort);
void addsarea (struct uplname **chain, struct uplname *tempor, char *areaname,
         short where, short wild);
void inecholog (char *areaname);
void delorph (struct uplname *utarea, struct uplname *ttname);
void delorphn (struct uplname *utarea, struct uplname *ttname, char * descr);
short delkill (short deltype);
void dolist (short rt);
void relink (void);
